import { Inter } from 'next/font/google';

import "@/assets/css/reset.css";
import "@/assets/css/globals.css";

const inter = Inter({ subsets: ['latin'] });

import clsx from 'clsx';

export const metadata = {
  title: 'TODO: Add title and description',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx(
        "bg-gray-100",
        inter.className
      )}>
        {children}

        <div id="portal"></div>
      </body>
    </html>
  );
}
